spring:
  profiles:
    active: local
    group:
      local: common, secret

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 100MB

server:
  tomcat:
    max-swallow-size: -1


springdoc:
  swagger-ui:
    path: doc

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.korit.post_mini_project_back.entity
